name: stylish
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.6.0
  dio: ^5.8.0+1
  eitherx: ^2.0.1
  flutter_rating_bar: ^4.0.1
  firebase_core: ^3.14.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_bloc: ^9.1.1
  flutter_launcher_icons: ^0.14.4
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  flutter_svg: ^2.1.0
  get_it: ^8.2.0
  go_router: ^15.1.3
  intl: any
  provider: ^6.1.5
  shared_preferences: ^2.5.3   # ← اتنقلت هنا
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^19.4.2
  permission_handler: ^12.0.1
  onesignal_flutter: ^5.3.4

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 500

flutter_native_splash:
  color: "#ffffff"
  image: assets/icons/splash_icon.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: scaleAspectFit

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/splash_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/splash_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/splash_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icons/splash_icon.png"

flutter_intl:
  enabled: true
  use_deferred_loading: false
