name: Flutter CI/CD

on:
  push:
    branches:
      - main
      - publish_to_firebase
     
  pull_request:
    branches:
      - main
      - publish_to_firebase

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout My Code 
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Use the Eclipse Temurin distribution
          java-version: '17'

      - name: Install Flutter Version 3.24.5
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5' # Use the required Flutter version

      - name: Install Dependencies
        run: flutter pub get
      - name: Run Our Test
        run: echo "Skipping tests (enable if needed)"

      - name: Build APK
        run: flutter build apk --release
      - run: ls build/app/outputs/flutter-apk


      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.APP_ID}} 
          serviceCredentialsFileContent: ${{secrets.GOOGLE_APPLICATION_CREDENTIAL}}
          groups: stylishTester
          file: build/app/outputs/flutter-apk/app-release.apk
      